<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
    <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
    <EnableMSTestRunner>false</EnableMSTestRunner>
    <AssemblyVersion>0.0.0.216</AssemblyVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RollForward>LatestMajor</RollForward>
    <!-- Declare this test assembly as Windows-only to suppress CA1416 warnings. -->
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MVS\MVS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ILLink\ILLink.Descriptors.LibraryBuild.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="MSTest.Analyzers" Version="4.3.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MSTest.TestAdapter" Version="4.3.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
  </ItemGroup>
</Project>
